<?php


namespace Tests\Unit;


use App\ToTest\Database\UserManager;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserManagerTest extends TestCase
{

    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        UserManager::write();
    }

    public function existingUsers() {
        return [
            ['John'],
            ['Clarisa'],
            ['Remy'],
            ['Jacky'],
            ['Daniel']
        ];
    }

    /**
     * @dataProvider existingUsers
     */

    public function testWring($userName) {
        $this->assertDatabaseHas('users',[
            'name' => $userName
        ]);
    }


    /**
     * @dataProvider existingUsers
     */
    public function testClearing($userName) {
        UserManager::delete();
        $this->assertDeleted('users',[
            'name' => $userName
        ]);
    }
}
